### ISSUE TITLE
BUG#PRODUCCION#  anular guias de remision no tiene  un indicador

### ISSUE THREAD

**Issue by emenesest** [Intel-ITCibercont/Issues-Soporte#111]
### Persona de contacto

EPIFANIA

### Software

FACTURADOR WEB

### Descripción.

al anular una guía de remisión en el sistema no hay un indicador de que esa guía haya sido anulada

**Comment by Skeyss** [comment]
Y a se creo un issue en web Anotando todas las revisiones que se tienen que hacer al anular una gua de remision
