### ISSUE TITLE
MEJORA#PRODUCCION#  CREACION DE PRODUCTO RAPIDO

### ISSUE THREAD

**Issue by TeoAntony** [Intel-ITCibercont/Issues-Soporte#67]
### Persona de contacto

TEO

### Software

RESTAURANTES ESCRITORIO

### Descripción.

QUE SE AGREGUE LA OPCION DE CREACION DE PRODUCTO RAPIDO

**Comment by Skeyss** [comment]
Se Verificado y se noto que no es necesario la creacion de producto rapidos 
por que en el modulo de restaurantes se necesita configurar varias parametros del producto
